"""empty message

Revision ID: 3299f84efa21
Revises: 
Create Date: 2022-08-01 00:15:43.519809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3299f84efa21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('memo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['memo_id'], ['memo.id'], name='likes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='likes_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'memo_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
